---
title: "writing_function"
author: "Paula Wu"
date: "11/4/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
```

# Z Score
```{r}
x_vec = rnorm(25, mean = 5, sd = 4)

(x_vec - mean(x_vec))/sd(x_vec)

z_score = function(x){
  z = (x-mean(x))/sd(x)
  return(z)
}

z_score(x = x_vec)

y_vec = rnorm(40, mean = 12, sd = .3)
z_score(x = y_vec)
```

How great is this?
```{r, eval = FALSE}
z_score(3)
z_scores("my name is jeff")
z_score(mtcars)
```
Let's try again
```{r}
z_score = function(x){
  if(is.numeric(x)){
    stop("x needs to be numeric")
  }
  if(length(x)<3){
    stop("x should be at least of length 3")
  }
  z = (x-mean(x))/sd(x)
  return(z)
}
```

```{r, error = TRUE}
# error = TRUE, intend to show the errors
z_score(3)
z_scores("my name is jeff")
z_score(mtcars)
```

## Multiple returns 
```{r}
mean_sd = function(x){
  if(!is.numeric(x)){
    stop("x needs to be numeric")
  }
  if(length(x)<3){
    stop("x should be at least of length 3")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  output_df = 
    tibble(
    mean = mean_x,
    sd = sd_x
  )
  return(output_df)
}

mean_sd(x_vec)
```

## Different sample sizes, means, sds

```{r}
stm_data = 
  tibble(
    x = rnorm(30, mean = 2, sd = 3)
  )

stm_data %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
  )
```
Let's write a function that simulates data, computes the mean and sd
```{r}
sim_mean_sd = function(n, mu, sigma){
  sim_data = 
  tibble(
    x = rnorm(n, mean = mu, sd = sigma)
  )

  sim_data %>% 
    summarize(
      mean = mean(x),
      sd = sd(x)
    )
}
sim_mean_sd(30,4,4)
```
```{r}
sim_mean_sd = function(n = 30, mu = 4, sigma = 3){
  sim_data = 
  tibble(
    x = rnorm(n, mean = mu, sd = sigma)
  )

  sim_data %>% 
    summarize(
      mean = mean(x),
      sd = sd(x)
    )
}
sim_mean_sd (20)
```

## Napolean dynamite
```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_elements(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_elements("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_elements(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)

```
Okay, but there are many pages of reviews

Write a function that gets reviews based on page url
```{r}
get_page_review = function(page_url){
  
  page_html = read_html(url)
  
  review_titles = 
    page_html %>%
    html_elements(".a-text-bold span") %>%
    html_text()
  
  review_stars = 
    page_html %>%
    html_elements("#cm_cr-review_list .review-rating") %>%
    html_text()
  
  review_text = 
    page_html %>%
    html_elements(".review-text-content span") %>%
    html_text()
  
  reviews = tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
  return(reviews)
}

url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"
get_page_review(url)

base_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
urls = str_c(base_url, 1:5)
bind_rows(
  get_page_review(urls[1]),
  get_page_review(urls[2]),
  get_page_review(urls[3]),
  get_page_review(urls[4]),
  get_page_review(urls[5])
)
```

